//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lend
    {
        public int Id { get; set; }
        public string BorrowerName { get; set; }
        public int LoanAmount { get; set; }
        public int RepaymentAmount { get; set; }
    }
}
